In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import confusion_matrix
import numpy as np

In [2]:
data=pd.read_table("/Users/shahzad/Documents/proteomics_analysis/apoe_association/protein_pheno.txt")

In [3]:
data=data.dropna()
X=data[['sex ','age_BC','APOE']]
Y=data[['AD']]

In [4]:
x_train, x_test, y_train, y_test = train_test_split(X, Y,train_size=0.75,random_state=0)

In [5]:
logReg=LogisticRegression()

In [6]:
logReg.fit(x_train,np.ravel(y_train))

LogisticRegression()

In [7]:
y_pred=logReg.predict(x_test)

In [8]:
confusion_matrix(y_test,y_pred)

array([[11, 28],
       [ 3, 34]])

In [9]:
print(metrics.recall_score(y_test,y_pred))

0.918918918918919


In [10]:

columns=data.columns.to_numpy()
columns=columns[3:20]
columns=np.concatenate((columns,['sex ']))

In [11]:
X=data[columns]
Y=data[['AD']]

In [12]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,train_size=0.9,random_state=0)

In [13]:
## Scaling the data will help to fit the model in Python 
## as data is also provided as columns so converting this into array using ravel function will avoid the error
from sklearn import preprocessing
scaler=preprocessing.StandardScaler().fit(X_train)
X_scaled = scaler.transform(X_train)

In [14]:
logistR=LogisticRegression()

In [15]:
logistR.fit(X_scaled,np.ravel(Y_train))

LogisticRegression()

In [16]:
predic_Y=logistR.predict(X_test)

In [17]:
metrics.accuracy_score(Y_test,predic_Y)

0.5483870967741935

In [18]:
####  KNN alogorithm on the iris dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
dataset = pd.read_csv(url, names=names)

In [19]:
dataset=pd.DataFrame(dataset)

In [20]:
dataset.columns

Index(['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class'], dtype='object')

In [21]:
dataset.index

RangeIndex(start=0, stop=150, step=1)

In [42]:
X=dataset.iloc[:,[0,1,2,3]].values
y=dataset.iloc[:,4].values

In [44]:
x_train, x_test, y_train, y_test =train_test_split(X, y, test_size=0.2)

In [46]:
x_test

array([[6.2, 2.8, 4.8, 1.8],
       [6.7, 3. , 5.2, 2.3],
       [6. , 2.2, 5. , 1.5],
       [7.2, 3.6, 6.1, 2.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.4, 2.7, 5.3, 1.9],
       [5.8, 2.8, 5.1, 2.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.9, 3. , 5.1, 1.8],
       [6.4, 2.9, 4.3, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [6. , 2.2, 4. , 1. ],
       [6.7, 3.3, 5.7, 2.5],
       [5.4, 3. , 4.5, 1.5],
       [5. , 3.5, 1.6, 0.6],
       [6.6, 2.9, 4.6, 1.3],
       [4.9, 3. , 1.4, 0.2],
       [5.6, 2.8, 4.9, 2. ],
       [5. , 3.3, 1.4, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [6.4, 3.1, 5.5, 1.8],
       [7.3, 2.9, 6.3, 1.8],
       [5.9, 3. , 4.2, 1.5],
       [5.7, 4.4, 1.5, 0.4],
       [5.1, 3.8, 1.9, 0.4],
       [5.4, 3.7, 1.5, 0.2],
       [5. , 3. , 1.6, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [6.8, 3.2, 5.9, 2.3],
       [6.3, 2.5, 5. , 1.9]])

In [47]:
from sklearn.preprocessing import StandardScaler

In [48]:
scaler=StandardScaler()
scaler.fit(x_train)

StandardScaler()

In [49]:
X_train=scaler.transform(x_train)

In [50]:
X_test=scaler.transform(x_test)

In [51]:
from sklearn.neighbors import KNeighborsClassifier

In [52]:
KNN= KNeighborsClassifier(n_neighbors=5)

In [53]:
KNN.fit(X_train,y_train)

KNeighborsClassifier()

In [54]:
y_pred=KNN.predict(X_test)

In [55]:
print(confusion_matrix(y_test, y_pred))

[[10  0  0]
 [ 0  7  0]
 [ 0  1 12]]


In [56]:
from sklearn.metrics import classification_report

In [57]:
print(classification_report(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.88      1.00      0.93         7
 Iris-virginica       1.00      0.92      0.96        13

       accuracy                           0.97        30
      macro avg       0.96      0.97      0.96        30
   weighted avg       0.97      0.97      0.97        30

